name: Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Deploy to Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |

            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 22
            npm install -g pm2

            cd /home/azureuser/leavems  
            git pull origin main
            npm ci
            
            node ace build
            cp .env build/.env
            cd build
            export NODE_ENV=production
            echo "NODE_ENV=production" >> .env
            npm ci --omit="dev" 
            
            # Update PM2 config and restart
            pm2 start leavems